<template>
  <el-table
    :data="unitEngineeringTableData"
    border
    stripe
    tooltip-effect="dark"
    style="width:100%"
    highlight-current-row
    @selection-change="handleSelectionChange">
    <el-table-column
      type="selection"
      width="55">
    </el-table-column>
    <el-table-column
      label="工程名称"
      prop="name"
      width="180"
      show-overflow-tooltip>
    </el-table-column>
    <el-table-column
      label="开工时间"
      prop="startingTime"
      width="180"
      show-overflow-tooltip>
    </el-table-column>
    <el-table-column
      label="建筑面积"
       width="180"
      prop="constructionArea"
      show-overflow-tooltip>
    </el-table-column>
    <el-table-column
      label="地上层数"
       width="180"
      prop="undergroundNum"
      show-overflow-tooltip>
    </el-table-column>
    <el-table-column
      label="地下层数"
       width="180"
      prop="overgroundNum"
      show-overflow-tooltip>
    </el-table-column>
    <el-table-column
      label="工程类别"
       width="180"
      prop="engineeringCategory"
      show-overflow-tooltip>
    </el-table-column>
    <el-table-column
      label="结构形式"
       width="180"
      prop="structureForm.description"
      show-overflow-tooltip>
    </el-table-column>
    <el-table-column
      label="单体装配率"
       width="180"
      prop="engineeringIndustrialization.unitAssemblyRate"
      show-overflow-tooltip>
    </el-table-column>
    <el-table-column
      label="外墙预制比例应用产业化技术的建筑面积"
       width="180"
      prop="engineeringIndustrialization.exteriorWallArea"
      show-overflow-tooltip>
    </el-table-column>
    <el-table-column
      label="预制外墙水平投影面积"
       width="180"
      prop="engineeringIndustrialization.wallShadowArea"
      show-overflow-tooltip>
    </el-table-column>
    <el-table-column
      label="不纳入地上容积率的建筑面积"
       width="180"
      prop="engineeringIndustrialization.conArea"
      show-overflow-tooltip>
    </el-table-column>
    <el-table-column
      label="应用结构类型"
       width="180"
      prop="engineeringIndustrialization.applicationStructureType.description"
      show-overflow-tooltip>
    </el-table-column>
    <el-table-column
      label="应用楼层范围"
       width="180"
      prop="engineeringIndustrialization.floorScope"
      show-overflow-tooltip>
    </el-table-column>
  </el-table>
</template>
<script>
  export default{
    data(){
      return{
        selectedRows:[],
      }
    },
    props:['unitEngineeringTableData'],
    methods:{
      handleSelectionChange(selectedRows){
        this.selectedRows = selectedRows
        this.$emit('handleSelectionChange',this.selectedRows)
      }
    }
  }
</script>
